language: node_js
node_js:
  - "12.4.0"
before_install:
  - touch .env
  - echo "REACT_APP_API_URL=http://192.168.1.228:8000" >> .env
install:
  - yarn install
cache:
  directories:
    - node_modules
script:
  - yarn test
